version: '3.2'
services:
  slas-api:
    image: maven-taln.upf.edu/welcome/slas_api:2023-02-03
    environment:
      - LANGUAGE_SERVICES_CONFIGURATION_JSON={"language_services_map":{"en":"http://slas-en:8080/slas-services-en/api/dla","ca":"http://slas-ca:8080/slas-services-ca/api/ca","de":"http://slas-de:8080/slas-services-de/api/de","el":"http://slas-el:8080/slas-services-el/api/el","es":"http://slas-es:8080/slas-services-es/api/es"}}
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      labels:
        - "traefik.frontend.rule=Host:welcome-slas.${DOMAIN}"
        - "traefik.port=8080"
  slas-demo:
    image: maven-taln.upf.edu/welcome/slas_demo:2023-02-03
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      labels:
        - "traefik.frontend.rule=Host:welcome-slas-demo.${DOMAIN}"
        - "traefik.port=8080"

  slas-en:
    image: maven-taln.upf.edu/welcome/slas_en:2023-02-03
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 20GB
      labels:
        - "traefik.frontend.rule=Host:welcome-slas-en.${DOMAIN}"
        - "traefik.port=8080"
    volumes:
      - type: bind
        source: "/resources/babelconfig-4.0.1"
        target: "/resources/babelconfig-4.0.1"
        read_only: true
      - type: bind
        source: "/resources/BabelNet-4.0.1"
        target: "/resources/BabelNet-4.0.1"
        read_only: true
      - type: bind
        source: "/resources/BabelNet-4.0.1_en.cache"
        target: "/resources/BabelNet-4.0.1_en.cache"
        read_only: true
      - type: bind
        source: "/resources/embeddings/cc.en.300.ra"
        target: "/resources/embeddings/cc.en.300.ra"
        read_only: true
#      - type: bind
#        source: "/resources/embeddings/glove.840B.300d.ra"
#        target: "/resources/glove.840B.300d.ra"
#        read_only: true
      - type: bind
        source: "/resources/disambiguation_properties-resources.en.txt"
        target: "/resources/disambiguation_properties-resources.en.txt"
        read_only: true
    environment:
      - DBPEDIA_ENDPOINT=http://spotlight-en.p.grivolla.net/rest
      #- CONCEPT_URL=http://concepts-en.p.grivolla.net
      - CONCEPT_URL=http://concepts-en-neural.p.grivolla.net
      - NER_URL=http://ner-spacy-en.p.grivolla.net
      - BABELNET_CONFIG=/resources/babelconfig-4.0.1
      - COMPACT_DICTIONARY=/resources/BabelNet-4.0.1_en.cache
      - DISAMBIGUATION_PROPS=/resources/disambiguation_properties-resources.en.txt
      - SPEECHACT_URL=https://welcome-project.upf.edu/dialogtag/
      - GEOLOCATION_URL=http://geolocation.p.grivolla.net/
      - TAXONOMY_PATH=/resources/taxonomy.ttl
      - TAXONOMY_SERVICE_URL=https://welcome-project.upf.edu/taxonomy/xml
      - JAVA_OPTS=-Xmx16g -Xms4g
      
  slas-ca:
    image: maven-taln.upf.edu/welcome/slas_ca:2023-02-03
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-slas-ca.${DOMAIN}"
        - "traefik.port=8080"
    environment:
      - JAVA_OPTS=-Xmx16g

  slas-es:
    image: maven-taln.upf.edu/welcome/slas_es:2023-02-03
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-slas-es.${DOMAIN}"
        - "traefik.port=8080"
    environment:
      - JAVA_OPTS=-Xmx16g

  slas-de:
    image: maven-taln.upf.edu/welcome/slas_de:2023-02-03
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-slas-de.${DOMAIN}"
        - "traefik.port=8080"
    environment:
      - JAVA_OPTS=-Xmx16g

  slas-el:
    image: maven-taln.upf.edu/welcome/slas_el:2023-02-03
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-slas-el.${DOMAIN}"
        - "traefik.port=8080"
    environment:
      - JAVA_OPTS=-Xmx16g

  dialogtag:
    image: maven-taln.upf.edu/uima_taln_dialogtag_en:2021-02-05
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-dialogtag.${DOMAIN}"
        - "traefik.port=8000"
  dms:
    image: registry.gitlab.com/talnupf/welcome/dms:2023-02-01
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-dms.${DOMAIN}"
        - "traefik.port=8080"
  nlg:
    image: registry.gitlab.com/talnupf/welcome/nlg:2023-01-31
    networks:
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-nlg.${DOMAIN}"
        - "traefik.port=8080"
    environment:
      - CONTENTDB_URL=http://3.20.64.60/welcome-praksis/integration/workflow/dispatcher/contentDBCollections
      #- CONTENTDB_URL=https://18.224.42.120/welcome/integration/workflow/dispatcher/contentDBCollections
  tts-en:
    image: registry.gitlab.com/talnupf/welcome/tts:2020-06-20
    networks:
      - traefik
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-tts-en.${DOMAIN}"
        - "traefik.port=80"
  speech2text-en:
    image: maven-taln.upf.edu/ingenious/speech2text_flashlight:2021-03-08
    networks:
      - traefik
    volumes:
      - /resources/projects/welcome/speech2text/en/RASR_20200305/ASR:/ASR
    environment: 
      - CONFIG_FILE=/ASR/conf/decode.cfg
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "4"
          memory: 10GB
      labels:
        - "traefik.frontend.rule=Host:en.asr.welcome.${DOMAIN}"
        - "traefik.port=80"
        - "traefik.enable=true"
  tts-wrapper:
    image: maven-taln.upf.edu/welcome/tts-wrapper:2023-01-31
    networks:
      - traefik
    volumes:
      - /resources/projects/welcome/tts_cache:/cache
    environment: 
      - CACHE_DIR=/cache/
    deploy:
      replicas: 1
      resources:
        limits:
            cpus: "2"
            memory: 2GB
      labels:
        - "traefik.frontend.rule=Host:welcome-tts.${DOMAIN}"
        - "traefik.port=80"
        - "traefik.enable=true"        
networks:
  traefik:
    external: true