version: '3.2'
services:
  las-en:
    image: maven-taln.upf.edu/welcome/dla:2021-07-16
    networks:
      - welcomenet
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 20GB
      labels:
        - "traefik.frontend.rule=Host:welcome-dla.${DOMAIN}"
        - "traefik.port=8080"
    volumes:
      - type: bind
        source: "/resources/babelconfig-4.0.1"
        target: "/resources/babelconfig-4.0.1"
        read_only: true
      - type: bind
        source: "/resources/BabelNet-4.0.1"
        target: "/resources/BabelNet-4.0.1"
        read_only: true
      - type: bind
        source: "/resources/BabelNet-4.0.1_en.cache"
        target: "/resources/BabelNet-4.0.1_en.cache"
        read_only: true
      - type: bind
        source: "/resources/embeddings/cc.en.300.ra"
        target: "/resources/embeddings/cc.en.300.ra"
        read_only: true
#      - type: bind
#        source: "/resources/embeddings/glove.840B.300d.ra"
#        target: "/resources/glove.840B.300d.ra"
#        read_only: true
      - type: bind
        source: "/resources/disambiguation_properties-resources.en.txt"
        target: "/resources/disambiguation_properties-resources.en.txt"
        read_only: true
    environment:
      - DBPEDIA_ENDPOINT=http://spotlight-en.p.taln.ml/rest
      #- CONCEPT_URL=http://concepts-en.p.taln.ml
      - CONCEPT_URL=http://concepts-en.v.taln.ml
      - NER_URL=http://ner-spacy-en.v.taln.ml
      - BABELNET_CONFIG=/resources/babelconfig-4.0.1
      - COMPACT_DICTIONARY=/resources/BabelNet-4.0.1_en.cache
      - DISAMBIGUATION_PROPS=/resources/disambiguation_properties-resources.en.txt
      - SPEECHACT_URL=https://welcome-project.upf.edu/dialogtag/
      - GEOLOCATION_URL=http://geolocation.v.taln.ml/
      - TAXONOMY_PATH=/resources/taxonomy.ttl
      - TAXONOMY_SERVICE_URL=https://welcome-project.upf.edu/taxonomy/xml
      - JAVA_OPTS=-Xmx16g -Xms4g -XX:MaxPermSize=1024m
  dialogtag:
    image: maven-taln.upf.edu/uima_taln_dialogtag_en:2021-02-05
    networks:
      - welcomenet
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-dialogtag.${DOMAIN}"
        - "traefik.port=8000"
  dms:
    image: registry.gitlab.com/talnupf/welcome/dms:2021-10-05
    networks:
      - welcomenet
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-dms.${DOMAIN}"
        - "traefik.port=8080"
  nlg:
    image: registry.gitlab.com/talnupf/welcome/nlg:2021-10-05
    networks:
      - welcomenet
      - traefik
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-nlg.${DOMAIN}"
        - "traefik.port=8080"
  tts-en:
    image: registry.gitlab.com/talnupf/welcome/tts:2020-06-20
    networks:
      - welcomenet
      - traefik
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-tts-en.${DOMAIN}"
        - "traefik.port=80"
  asr:
    image: maven-taln.upf.edu/welcome/but-asr-en:v20210610
    networks:
      - welcomenet
      - traefik
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "4"
          memory: 4GB
      labels:
        - "traefik.frontend.rule=Host:welcome-asr.${DOMAIN}"
        - "traefik.port=9080"
  speech2text-en:
    image: maven-taln.upf.edu/ingenious/speech2text_flashlight:2021-03-08
    networks:
      - traefik
    volumes:
      - /resources/projects/welcome/speech2text/en/RASR_20200305/ASR:/ASR
    environment: 
      - CONFIG_FILE=/ASR/conf/decode.cfg
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "4"
          memory: 10GB
      labels:
        - "traefik.frontend.rule=Host:en.asr.welcome.${DOMAIN}"
        - "traefik.port=80"
        - "traefik.enable=true"
  tts-wrapper:
    image: maven-taln.upf.edu/welcome/tts-wrapper:2021-10-12
    networks:
      - traefik
    volumes:
      - /resources/projects/welcome/tts_cache:/cache
    environment: 
      - CACHE_DIR=/cache/
    deploy:
      replicas: 1
      resources:
        limits:
            cpus: "2"
            memory: 2GB
      labels:
        - "traefik.frontend.rule=Host:welcome-tts.${DOMAIN}"
        - "traefik.port=80"
        - "traefik.enable=true"        
networks:
  welcomenet:
  traefik:
    external: true