package edu.upf.taln.welcome.slas.commons.analysis;

public enum FlowStepName {
	PARSING, 
	SSYNTS,
	NER,
	NER_RETOKENIZER,
	CONCEPT_CANDIDATES,
	CONCEPT_DESAMBIGUATION, 
	RETOKENIZER,
	DSYNTS, 
	DBPEDIA,
	DBPEDIA_RETOKENIZER,
    EMOTION,
    SPEECHACT,
    GEOLOCATION,
    GEOLOCATION_RETOKENIZER,
    TAXONOMY,
    TAXONOMY_RETOKENIZER,
    HEIDELTIME,
    HEIDELTIME_RETOKENIZER,
    NUMBER_SEQUENCE,
    NUMBER_SEQUENCE_RETOKENIZER
}
